blank_issues_enabled: true
contact_links:
  - name: Questions & Open-Ended Ideas
    url: https://github.com/orgs/praxis-proxy/discussions
    about: For questions or ideas you're not ready to file. To propose an enhancement, open an issue instead.
